# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lronnet <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/12/29 19:33:29 by lronnet           #+#    #+#              #
#    Updated: 2019/12/29 19:33:31 by lronnet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = buff_op.c\
doprintf.c\
ft_printf.c\
get_flgstkns.c\
init.c\
put_char.c\
put_exp.c\
put_float.c\
put_ptr.c\
put_sign_int2.c\
put_sign_int.c\
put_str.c\
put_unsign_int2.c\
put_unsign_int.c\
switch_exp.c\
switch_float.c\
switch_int.c\
switch_uint.c\
utils.c\
valid_seq.c

include ../_templates/make_template


