# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lronnet <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/12/29 19:34:43 by lronnet           #+#    #+#              #
#    Updated: 2019/12/29 19:34:45 by lronnet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = \
ft_arri_inssort.c\
ft_atoi.c\
ft_bzero.c\
ft_comp_asc.c\
ft_comp_desc.c\
ft_isalnum.c\
ft_isalpha.c\
ft_isascii.c\
ft_isdigit.c\
ft_islower.c\
ft_isprint.c\
ft_isupper.c\
ft_iswap.c\
ft_itoa.c\
ft_ll_add_first.c\
ft_ll_add_last.c\
ft_ll_add_n.c\
ft_ll_get.c\
ft_ll_get_first.c\
ft_ll_get_last.c\
ft_ll_get_n.c\
ft_ll_length.c\
ft_ll_new_node.c\
ft_ll_peek.c\
ft_ll_peek_first.c\
ft_ll_peek_last.c\
ft_ll_peek_n.c\
ft_ll_pop.c\
ft_ll_push.c\
ft_lstadd.c\
ft_lstdel.c\
ft_lstdelone.c\
ft_lstiter.c\
ft_lstmap.c\
ft_lstnew.c\
ft_mathfact.c\
ft_mathiabs.c\
ft_mathldabs.c\
ft_mathllabs.c\
ft_mathpow.c\
ft_mathsqrt.c\
ft_memalloc.c\
ft_memccpy.c\
ft_memchr.c\
ft_memcmp.c\
ft_memcpy.c\
ft_memdel.c\
ft_memmove.c\
ft_memset.c\
ft_putchar.c\
ft_putchar_fd.c\
ft_putendl.c\
ft_putendl_fd.c\
ft_putnbr.c\
ft_putnbr_fd.c\
ft_putstr.c\
ft_putstr_fd.c\
ft_sizenbr.c\
ft_strcat.c\
ft_strchr.c\
ft_strclr.c\
ft_strcmp.c\
ft_strcpy.c\
ft_strdel.c\
ft_strdup.c\
ft_strequ.c\
ft_striter.c\
ft_striteri.c\
ft_strjoin.c\
ft_strlcat.c\
ft_strlen.c\
ft_strmap.c\
ft_strmapi.c\
ft_strncat.c\
ft_strncmp.c\
ft_strncpy.c\
ft_strnequ.c\
ft_strnew.c\
ft_strnstr.c\
ft_strrchr.c\
ft_strsplit.c\
ft_strstr.c\
ft_strsub.c\
ft_strtrim.c\
ft_tolower.c\
ft_toupper.c\
ft_sizenbr.c

include ../_templates/make_template
